# --- basic ---
title: "Portfolio"
description: "Projects, certifications, and weekly notes from my path into IT / SysAdmin."

# --- theme ---
remote_theme: just-the-docs/just-the-docs@main
color_scheme: dark   # optional

# --- navigation order ---
nav_sort: case_insensitive
aux_links:
  "LinkedIn": "https://www.linkedin.com/in/ash-kuhlmann-970271214/"

collections:
  projects:
    output: true
    permalink: /projects/:title.html
  journal:
    output: true
    permalink: /journal/:year-:month-:day-:title.html

plugins:
  - jekyll-remote-theme

